### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by pjmartorell** [dotcypress/GitHubMarkdownPreview#27]
I have Python 2.7 installed and I have this issue related to the name of a module of Python 3:

```
Reloading plugin /Users/johndoe/Library/Application Support/Sublime Text 2/Packages/GitHubMarkdownPreview-master/GHMarkdownPreview.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./GHMarkdownPreview.py", line 8, in <module>
    import urllib.parse
ImportError: No module named parse
```

**Comment by pjmartorell** [comment]
Modifying the `import urllib.parse` for `from urlparse import urlparse` seems to fix the previous bug but after running it I get a "error: Error in GitHubMarkdownPreview package:" with no explanation.
